codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        base: auto
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no

ignore:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/test/**'
  - '**/tests/**'
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/node_modules/**'
  - 'examples/**'
  - 'playgrounds/**'
  - '**/*.d.ts'
