packages:
  - 'examples/*'
  - 'playgrounds/*'
  - 'playgrounds/router/routes/*'
  - 'playgrounds/widget/packages/*'
  - 'packages/*'
  - 'internal/*'

catalog:
  '@types/jest': ^29.5.12
  '@jest/globals': ^29.7.0
  '@types/node': '^22.2.0'
  '@edge-runtime/vm': ^5.0.0
  'vite': ^5.4.10
  'vitest': ^2.1.9
  'tsup': ^8.3.4
  'jest': ^29.7.0
  'ts-jest': 29.2.1
  'jest-environment-miniflare': ^2.14.4
  'miniflare': ^4.20250409.0
  'typescript': ^5.5.4
  '@rollup/pluginutils': ^5.1.4
