packages:
  - 'examples/*'
  - 'examples/web-router/routes/*'
  - 'examples/web-widget/packages/*'
  - 'packages/*'
  - 'internal/*'

catalog:
  'vite': ^5.4.0
  'vitest': ^2.0.5
  '@types/node': '^22.2.0'
  'tsup': ^8.2.4
