export type SnapshotRoute = [
  pathname: string,
  status?: number,
  replace?: (body: string) => string,
];

export const SNAPSHOT_ROUTES: SnapshotRoute[] = [
  ['/background-tasks'],
  ['/client-only-component'],
  ['/css-lazy-dynamic'],
  ['/custom-handlers'],
  ['/experimental-async-component'],
  ['/fallback'],
  ['/fallback?404', 404],
  ['/fallback?500', 500],
  ['/fallback?global-404', 404],
  ['/fallback?global-500', 500],
  [
    '/fetching-data',
    200,
    (body: string) => body.replace(/<script>.*?<\/script>/gs, ''),
  ],
  ['/form'],
  ['/'],
  ['/meta'],
  ['/streaming/react/shell-error', 500],
  ['/streaming/html/shell-error', 500],
  ['/streaming/vue3/shell-error', 500],
  ['/streaming/solid/shell-error', 500],
  ['/streaming/preact/shell-error', 500],
  ['/shadow-dom'],
  ['/shadow-dom/react'],
  ['/shadow-dom/html'],
  ['/shadow-dom/vue3'],
  ['/shadow-dom/vue2'],
  ['/shadow-dom/svelte'],
  ['/shadow-dom/solid'],
  ['/shadow-dom/preact'],
  // Streaming routes (/streaming/*) are verified in
  // streaming.test.ts — their DOM structure is non-deterministic.
  ['/large-css'],
  // TODO: Fix the issue with the React import widgets.
  // ['/react-import-widgets'],
  ['/dynamic-routes', 404],
  ['/dynamic-routes/1'],
  ['/vue2-import-widgets'],
  ['/vue3-import-widgets'],
  ['/vue2-router'],
  ['/vue2-router/about'],
  ['/vue3-router'],
  ['/vue3-router/about'],
  ['/api/hello-world'],
  ['/api/mock-users?username=react'],
];
