export type SnapshotRoute = [
  pathname: string,
  status?: number,
  replace?: (body: string) => string,
];

export const SNAPSHOT_ROUTES: SnapshotRoute[] = [
  ['/background-tasks'],
  ['/client-only-component'],
  ['/css-lazy-dynamic'],
  ['/custom-handlers'],
  ['/experimental-async-component'],
  ['/fallback'],
  ['/fallback?404', 404],
  ['/fallback?500', 500],
  ['/fallback?global-404', 404],
  ['/fallback?global-500', 500],
  [
    '/fetching-data',
    200,
    (body: string) => body.replace(/<script>.*?<\/script>/gs, ''),
  ],
  ['/form'],
  ['/'],
  ['/lit-html-template'],
  ['/html-widget-islands'],
  ['/meta'],
  ['/react-and-vue'],
  ['/react-shell-error', 500],
  ['/html-shell-error', 500],
  ['/vue3-shell-error', 500],
  ['/vue-module-css'],
  ['/react-server-component'],
  // Streaming routes (/react-streaming, /vue3-streaming) are verified in
  // streaming.test.ts — their DOM structure is non-deterministic.
  ['/style'],
  ['/large-css'],
  // TODO: Fix the issue with the React import widgets.
  // ['/react-import-widgets'],
  ['/dynamic-routes', 404],
  ['/dynamic-routes/1'],
  ['/vue2-server-component'],
  ['/vue3-server-component'],
  ['/vue2-import-widgets'],
  ['/vue3-import-widgets'],
  ['/vue2-router'],
  ['/vue2-router/about'],
  ['/vue3-router'],
  ['/vue3-router/about'],
  ['/api/hello-world'],
  ['/api/mock-users?username=react'],
];
