import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Options } from 'tsup';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DIST = 'dist';
const NAME = 'web-router.server';
const PLACEHOLDER_NAME = 'placeholder';
const PLACEHOLDER_PATH = path.resolve(
  __dirname,
  DIST,
  `${PLACEHOLDER_NAME}.d.ts`
);
const PLACEHOLDER_CODE = `interface Framework {
  /**
   * Built-in client assets for the framework.
   */
  meta: import('./${NAME}.d.ts').Meta;
  /**
   * Service module manifest.
   */
  manifest: import('./${NAME}.d.ts').Manifest;
}
interface ImportMeta {
  /**
   * Assets injected by the framework.
   * This object is generated by the build tool.
   */
  readonly framework: Framework;
}`;

export const tsup: Options = {
  entry: {
    [NAME]: 'src/index.ts',
  },
  dts: {
    banner: `/// <reference path="./${PLACEHOLDER_NAME}.d.ts" />`,
  },
  target: 'es2022',
  splitting: true,
  sourcemap: false,
  format: ['esm'],
  outDir: DIST,
  // NOTE: Prevent `placeholder.d.ts` files from being cleaned up.
  clean: false,
  external: [],
  onSuccess: async () => {
    try {
      await fs.writeFile(PLACEHOLDER_PATH, PLACEHOLDER_CODE, 'utf8');
    } catch (error: any) {
      error.message = `Failed to create file: ${error.message}`;
      throw error;
    }
  },
};
