import type { Meta } from '@web-widget/schema';

type Module = unknown | (() => Promise<unknown>);
interface Manifest {
  dev?: boolean;
  routes: {
    module: Module;
    name?: string;
    pathname: string;
  }[];
  actions: {
    module: Module;
    name?: string;
    pathname: string;
  }[];
  middlewares: {
    module: Module;
    name?: string;
    pathname: string;
  }[];
  fallbacks: {
    module: Module;
    name?: string;
    pathname: string;
    status: number;
  }[];
  layout: {
    module: Module;
  };
}

/**
 * Placeholder for the meta object.
 * This module is generated by the build tool.
 */
export const meta: Meta = {};

/**
 * Placeholder for the manifest object.
 * This module is generated by the build tool.
 */
export const manifest: Manifest = {} as Manifest;

throw new Error(
  '@web-widget/helpers/placeholder: The build tool does not correctly implement this module.'
);
