// DO NOT EDIT. This file is generated by @web-widget/web-server.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $ROUTE0 from "./routes/about";
import * as $ROUTE1 from "./routes/index";
import * as $ISLAND0 from "./islands/Counter";
import * as $MIDDLEWARE0 from "./routes/_middleware";

import * as $NOTFOUND from "./routes/_404";



export const routes = [
  {
    file: "./routes/about.tsx",
    name: "about",
    pathname: "/about",
    module: $ROUTE0,
  },
  {
    file: "./routes/index.tsx",
    name: "index",
    pathname: "/",
    module: $ROUTE1,
  },
];

export const islands = [
  {
    file: "./islands/Counter.tsx",
    id: "counter",
    name: "Counter",
    module: $ISLAND0,
  },
];

export const middlewares = [
  {
    file: "./routes/_middleware.ts",
    pathname: "{/*}?",
    module: $MIDDLEWARE0,
  },
];



export const notFound = {
  file: "./routes/_404.tsx",
  name: "_404",
  pathname: "/_404",
  module: $NOTFOUND,
};

